<template>
  <q-form greedy ref="formEditRepairMsp">
    <q-dialog
      v-model="storeMspRepairs.isShowRepairEditDialog"
      persistent
      :maximized="$q.platform.is.mobile ? true : false"
      transition-show="slide-up"
      transition-hide="slide-down"
    >
      <q-card>
        <q-card-section class="row items-center no-wrap">
          <div class="text-h6">
            Ремонт МСП ({{ storeMspRepairs.curEditRepairMsp.serialNumber }} /
            {{ storeMspRepairs.curEditRepairMsp.yearManufacture }})
          </div>
        </q-card-section>
        <q-separator />

        <q-card-section class="row items-center justify-center">
          <div class="q-gutter-md">
            <q-select
              outlined
              clearable
              v-model="storeMspRepairs.curEditRepairTypeRepairModelValue"
              :options="storeMspRepairs.typeRepairs"
              option-value="id"
              option-label="name"
              emit-value
              map-options
              label="Тип ремонта"
            />

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeMspRepairs.curEditRepairPosRemovedModelValue"
              :options="storeMspRepairs.curEditRepairPosRemovedOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              @filter="filterQselPositionsRemoved"
              @update:model-value="onChangeQselPositionsRemoved"
              label="Позиция демонтажа"
            >
              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeMspRepairs.curEditRepairPosInstalledModelValue"
              :options="storeMspRepairs.curEditRepairPosInstalledOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              @filter="filterQselPositionsInstalled"
              @update:model-value="onChangeQselPositionsInstalled"
              label="Позиция установки"
            >
              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <div
              class="q-px-lg"
              v-if="
                storeMspRepairs.getTypeRepairById(
                  storeMspRepairs.curEditRepairTypeRepairModelValue
                )?.name == 'ТР' ||
                storeMspRepairs.getTypeRepairById(
                  storeMspRepairs.curEditRepairTypeRepairModelValue
                )?.name == 'КР'
              "
            >
              <q-btn
                label="Generate values"
                color="primary"
                icon="auto_awesome"
                outline
                v-model="modelValueAutoGenVal"
                @click="onIsAutoGeneratedValues"
              />
              <br /><br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeMspRepairs.curEditRepair.ro_8_7"
                label="ro_8_7 (Ом)"
                :rules="[
                  (val) =>
                    (val >= 93 - 12 && val <= 93 + 12) ||
                    `Сопротивление катушки индуктивности от ${93 - 12} Ом до ${
                      93 + 12
                    } Ом`,
                ]"
              >
                <q-tooltip>
                  {{
                    `Сопротивление катушки индуктивности от ${93 - 12} Ом до ${
                      93 + 12
                    } Ом`
                  }}
                </q-tooltip>
              </q-input>

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeMspRepairs.curEditRepair.ro_8_9"
                label="ro_8_9 (Ом)"
                :rules="[
                  (val) =>
                    (val >= 93 - 12 && val <= 93 + 12) ||
                    `Сопротивление катушки индуктивности от ${93 - 12} Ом до ${
                      93 + 12
                    } Ом`,
                ]"
              >
                <q-tooltip>
                  {{
                    `Сопротивление катушки индуктивности от ${93 - 12} Ом до ${
                      93 + 12
                    } Ом`
                  }}
                </q-tooltip>
              </q-input>

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeMspRepairs.curEditRepair.voltage"
                label="Напряжение питания (В)"
                :rules="[
                  (val) =>
                    (val >= 187 && val <= 242) ||
                    'Напряжение питания должно быть от 187 В до 242 В',
                ]"
                @update:model-value="onChangeVoltage"
              >
                <q-tooltip>
                  {{ `Напряжение питания должно быть от 187 В до 242 В` }}
                </q-tooltip>
              </q-input>

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeMspRepairs.curEditRepair.current"
                label="Потребляемый ток (мА)"
                :rules="[
                  (val) =>
                    (val >= 37 && val <= 48) ||
                    'Потребляемый ток должнен быть от 37 мА до 48 мА',
                ]"
                @update:model-value="onChangeCurrent"
              >
                <q-tooltip>
                  {{ `Потребляемый ток должнен быть от 37 мА до 48 мА` }}
                </q-tooltip>
              </q-input>

              <q-input
                outlined
                clearable
                readonly
                type="number"
                v-model="storeMspRepairs.curEditRepair.power"
                label="Потребляемая мощность (ВА)"
                :rules="[
                  (val) =>
                    val <= 9 || 'Потребляемая мощность должна быть ≤ 9 ВА',
                ]"
              >
                <q-tooltip>
                  {{ `Потребляемая мощность должна быть ≤ 9 ВА` }}
                </q-tooltip>
              </q-input>
            </div>

            <q-input
              outlined
              clearable
              v-model="storeMspRepairs.curEditRepair.dateRepair"
              label-slot
              mask="##.##.####"
            >
              <template v-slot:label>
                <q-icon name="calendar_today" /> Дата ремонта
              </template>
              <template v-slot:append>
                <q-icon name="event" class="cursor-pointer">
                  <q-popup-proxy
                    ref="qDateProxy"
                    cover
                    transition-show="scale"
                    transition-hide="scale"
                  >
                    <q-date
                      v-model="storeMspRepairs.curEditRepair.dateRepair"
                      mask="DD.MM.YYYY"
                    >
                      <div class="row items-center justify-end">
                        <q-btn
                          v-close-popup
                          label="Close"
                          color="primary"
                          flat
                        />
                      </div>
                    </q-date>
                  </q-popup-proxy>
                </q-icon>
              </template>
            </q-input>

            <q-input
              outlined
              clearable
              v-model="storeMspRepairs.curEditRepair.desc"
              label="desc"
              type="textarea"
            />

            <q-select
              outlined
              clearable
              multiple
              use-chips
              stack-label
              v-model="storeMspRepairs.curEditRepairWorkersModelValue"
              :options="storeWorkers.workers"
              option-value="id"
              :option-label="
                (item) =>
                  item === null
                    ? 'Null value'
                    : `${item?.nameSecond} ${item?.nameFirst} ${item?.nameMiddle}`
              "
              emit-value
              map-options
              label="Исполнители"
            />

            <q-item dense>
              <span class="text-weight-bold text-red">*</span>
              Indicates required fields
            </q-item>
          </div>
        </q-card-section>

        <q-separator />
        <q-card-actions align="right">
          <q-btn label="Cancel" color="primary" v-close-popup />
          <q-btn
            v-if="storeMspRepairs.curEditRepair.id"
            label="Update"
            color="amber-14"
            text-color="black"
            @click="onUpdateRepair"
          />
          <q-btn v-else label="Save" color="positive" @click="onSaveRepair" />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </q-form>
</template>

<script>
import { useQuasar } from "quasar";
import { defineComponent, ref } from "vue";
import { useMspRepairsStore } from "stores/equipments/msp/mspRepairs";
import { usePositionsStore } from "stores/positions";
import { useWorkersStore } from "stores/workers";
import * as utils from "src/utils";

export default defineComponent({
  name: "MspFormRepairEdit",

  setup() {
    const $q = useQuasar();
    const storeMspRepairs = useMspRepairsStore();
    const storePositions = usePositionsStore();
    const storeWorkers = useWorkersStore();

    let formEditRepairMsp = ref(null);
    let modelValueAutoGenVal = ref(null);

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsRemoved = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeMspRepairs.curEditRepairPosRemovedOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsRemoved = (val) => {
      storeMspRepairs.curEditRepair.fkPosRemovedId = val || null;
    };

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsInstalled = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeMspRepairs.curEditRepairPosInstalledOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsInstalled = (val) => {
      storeMspRepairs.curEditRepair.fkPosInstalledId = val || null;
    };

    /**
     *
     */
    const onIsAutoGeneratedValues = () => {
      storeMspRepairs.curEditRepair.ro_8_7 = utils.getRandomBetween(92, 104);
      storeMspRepairs.curEditRepair.ro_8_9 = utils.getRandomBetween(92, 104);
      storeMspRepairs.curEditRepair.voltage = utils.getRandomBetween(205, 230);
      storeMspRepairs.curEditRepair.current = utils.getRandomBetween(37, 39);
      storeMspRepairs.curEditRepair.power =
        (storeMspRepairs.curEditRepair.voltage *
          storeMspRepairs.curEditRepair.current) /
        1000;
    };

    /**
     *
     * @param {*} val
     */
    const onChangeVoltage = (val) => {
      let voltage = parseFloat(storeMspRepairs.curEditRepair.voltage) || 0;
      let current = parseFloat(storeMspRepairs.curEditRepair.current) || 0;

      storeMspRepairs.curEditRepair.power = (voltage * current) / 1000;
    };

    /**
     *
     * @param {*} val
     */
    const onChangeCurrent = (val) => {
      let voltage = parseFloat(storeMspRepairs.curEditRepair.voltage) || 0;
      let current = parseFloat(storeMspRepairs.curEditRepair.current) || 0;

      storeMspRepairs.curEditRepair.power = (voltage * current) / 1000;
    };

    /**
     *
     */
    const prepareRepairBeforeSaveUpdate = () => {
      storeMspRepairs.curEditRepair.fkTypeRepairId =
        storeMspRepairs.curEditRepairTypeRepairModelValue;
      storeMspRepairs.curEditRepair.fkWorkersIds = [
        ...storeMspRepairs.curEditRepairWorkersModelValue,
      ];

      storeMspRepairs.curEditRepair.fkMspId =
        storeMspRepairs.curEditRepairMsp.id;

      let typeRepair = storeMspRepairs.getTypeRepairById(
        storeMspRepairs.curEditRepairTypeRepairModelValue
      )?.name;

      // clear unused vars for selected type repair
      if (typeRepair == "ТО") {
        storeMspRepairs.curEditRepair.ro_8_7 = undefined;
        storeMspRepairs.curEditRepair.ro_8_9 = undefined;
        storeMspRepairs.curEditRepair.voltage = undefined;
        storeMspRepairs.curEditRepair.current = undefined;
        storeMspRepairs.curEditRepair.power = undefined;
      }
    };

    /**
     *
     */
    const onSaveRepair = () => {
      prepareRepairBeforeSaveUpdate();

      storeMspRepairs.saveRepair({
        mspRepair: storeMspRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "Msp repair has been added",
          });

          storeMspRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    /**
     *
     */
    const onUpdateRepair = () => {
      prepareRepairBeforeSaveUpdate();

      storeMspRepairs.updateRepair({
        mspRepair: storeMspRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "Msp repair has been updated",
          });

          storeMspRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    return {
      storeMspRepairs,
      storePositions,
      storeWorkers,
      formEditRepairMsp,
      modelValueAutoGenVal,
      filterQselPositionsRemoved,
      onChangeQselPositionsRemoved,
      filterQselPositionsInstalled,
      onChangeQselPositionsInstalled,
      onIsAutoGeneratedValues,
      onUpdateRepair,
      onSaveRepair,
      onChangeVoltage,
      onChangeCurrent,
    };
  },
});
</script>
