<template>
  <q-form greedy ref="formEditRepairImMeo">
    <q-dialog
      v-model="storeImMeoRepairs.isShowRepairEditDialog"
      persistent
      :maximized="$q.platform.is.mobile ? true : false"
      transition-show="slide-up"
      transition-hide="slide-down"
    >
      <q-card>
        <q-card-section class="row items-center no-wrap">
          <div class="text-h6">
            Ремонт им. Мотор ({{
              storeImMeoRepairs.curEditRepairImMeo.serialNumber
            }}
            / {{ storeImMeoRepairs.curEditRepairImMeo.yearManufacture }})
          </div>
        </q-card-section>
        <q-separator />

        <q-card-section class="row items-center justify-center">
          <div class="q-gutter-md">
            <q-select
              outlined
              clearable
              v-model="storeImMeoRepairs.curEditRepairTypeRepairModelValue"
              :options="storeImMeoRepairs.typeRepairs"
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              option-value="id"
              option-label="name"
              emit-value
              map-options
              label="Тип ремонта"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Тип ремонта
              </template>
            </q-select>

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeImMeoRepairs.curEditRepairPosRemovedModelValue"
              :options="storeImMeoRepairs.curEditRepairPosRemovedOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              @filter="filterQselPositionsRemoved"
              @update:model-value="onChangeQselPositionsRemoved"
              label="Позиция демонтажа"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Позиция демонтажа
              </template>

              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeImMeoRepairs.curEditRepairPosInstalledModelValue"
              :options="storeImMeoRepairs.curEditRepairPosInstalledOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              @filter="filterQselPositionsInstalled"
              @update:model-value="onChangeQselPositionsInstalled"
              label="Позиция установки"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Позиция установки
              </template>

              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <div
              class="q-px-lg"
              v-if="
                storeImMeoRepairs.getTypeRepairById(
                  storeImMeoRepairs.curEditRepairTypeRepairModelValue
                )?.name == 'ТР' ||
                storeImMeoRepairs.getTypeRepairById(
                  storeImMeoRepairs.curEditRepairTypeRepairModelValue
                )?.name == 'КР'
              "
            >
              <q-btn
                label="Generate values"
                color="primary"
                icon="auto_awesome"
                outline
                v-model="modelValueAutoGenVal"
                @click="onIsAutoGeneratedValues"
              />
              <br /><br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.resistanceGrounding"
                label-slot
                hint="Сопротивление заземления, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление заземления, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.resistanceWindingAB"
                label-slot
                hint="Сопротивление обмоток статора A-B, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора A-B, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.resistanceWindingBC"
                label-slot
                hint="Сопротивление обмоток статора B-С, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора B-С, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.resistanceWindingAC"
                label-slot
                hint="Сопротивление обмоток статора A-С, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора A-С, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.resistanceInsulation"
                label-slot
                hint="Сопротивление изоляции, (МОм)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление изоляции, (МОм)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.currentUpClose"
                label-slot
                hint="Показания УП при закрытом клапане, (мA)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Показания УП при закрытом клапане, (мA)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.currentUpOpen"
                label-slot
                hint="Показания УП при открытом клапане, (мA)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Показания УП при открытом клапане, (мA)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMeoRepairs.curEditRepair.current"
                label-slot
                hint="Рабочий ток, (А)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Рабочий ток, (А)
                </template>
              </q-input>
              <br />
            </div>

            <q-input
              outlined
              clearable
              v-model="storeImMeoRepairs.curEditRepair.dateRepair"
              label-slot
              mask="##.##.####"
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                <q-icon name="calendar_today" /> Дата ремонта
              </template>
              <template v-slot:append>
                <q-icon name="event" class="cursor-pointer">
                  <q-popup-proxy
                    ref="qDateProxy"
                    cover
                    transition-show="scale"
                    transition-hide="scale"
                  >
                    <q-date
                      v-model="storeImMeoRepairs.curEditRepair.dateRepair"
                      mask="DD.MM.YYYY"
                    >
                      <div class="row items-center justify-end">
                        <q-btn
                          v-close-popup
                          label="Close"
                          color="primary"
                          flat
                        />
                      </div>
                    </q-date>
                  </q-popup-proxy>
                </q-icon>
              </template>
            </q-input>

            <q-input
              outlined
              clearable
              v-model="storeImMeoRepairs.curEditRepair.desc"
              label="desc"
              type="textarea"
            />

            <q-select
              outlined
              clearable
              multiple
              use-chips
              stack-label
              v-model="storeImMeoRepairs.curEditRepairWorkersModelValue"
              :options="storeWorkers.workers"
              option-value="id"
              :option-label="
                (item) =>
                  item === null
                    ? 'Null value'
                    : `${item?.nameSecond} ${item?.nameFirst} ${item?.nameMiddle}`
              "
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              label="Исполнители"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                <q-icon name="perm_identity" /> Исполнители
              </template>
            </q-select>
          </div>
        </q-card-section>

        <q-card-section>
          <span class="text-weight-bold text-red">*</span>
          Indicates required fields
        </q-card-section>

        <q-separator />
        <q-card-actions align="right">
          <q-btn label="Cancel" color="primary" v-close-popup />
          <q-btn
            v-if="storeImMeoRepairs.curEditRepair.id"
            label="Update"
            color="amber-14"
            text-color="black"
            @click="onUpdateRepair"
          />
          <q-btn v-else label="Save" color="positive" @click="onSaveRepair" />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </q-form>
</template>

<script>
import { useQuasar } from "quasar";
import { defineComponent, ref } from "vue";
import { useImMeoRepairsStore } from "stores/equipments/imMeo/imMeoRepairs";
import { usePositionsStore } from "stores/positions";
import { useWorkersStore } from "stores/workers";
import * as utils from "src/utils";

export default defineComponent({
  name: "ImMeoFormRepairEdit",

  setup() {
    const $q = useQuasar();
    const storeImMeoRepairs = useImMeoRepairsStore();
    const storePositions = usePositionsStore();
    const storeWorkers = useWorkersStore();

    let formEditRepairImMeo = ref(null);
    let modelValueAutoGenVal = ref(null);

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsRemoved = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeImMeoRepairs.curEditRepairPosRemovedOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsRemoved = (val) => {
      storeImMeoRepairs.curEditRepair.fkPosRemovedId = val || null;
    };

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsInstalled = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeImMeoRepairs.curEditRepairPosInstalledOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsInstalled = (val) => {
      storeImMeoRepairs.curEditRepair.fkPosInstalledId = val || null;
    };

    /**
     *
     */
    const onIsAutoGeneratedValues = () => {
      storeImMeoRepairs.curEditRepair.resistanceGrounding = parseFloat(
        `${utils.getRandomBetween(1, 3)}.${utils.getRandomBetween(1, 89)}`
      );

      // FIXME : Find normal odds for resistanceWinding
      let resistanceWinding = utils.getRandomBetween(1, 10);
      storeImMeoRepairs.curEditRepair.resistanceWindingAB = resistanceWinding;
      storeImMeoRepairs.curEditRepair.resistanceWindingBC = resistanceWinding;
      storeImMeoRepairs.curEditRepair.resistanceWindingAC = resistanceWinding;

      storeImMeoRepairs.curEditRepair.resistanceInsulation =
        utils.getRandomBetween(1, 10) * 1000;

      storeImMeoRepairs.curEditRepair.currentUpClose = parseFloat(
        `0.${utils.getRandomBetween(3, 5)}`
      );
      storeImMeoRepairs.curEditRepair.currentUpOpen = parseFloat(
        `4.9${utils.getRandomBetween(0, 7)}`
      );
    };

    /**
     *
     */
    const prepareRepairBeforeSaveUpdate = () => {
      storeImMeoRepairs.curEditRepair.fkTypeRepairId =
        storeImMeoRepairs.curEditRepairTypeRepairModelValue;
      storeImMeoRepairs.curEditRepair.fkWorkersIds = [
        ...storeImMeoRepairs.curEditRepairWorkersModelValue,
      ];

      storeImMeoRepairs.curEditRepair.fkImMeoId =
        storeImMeoRepairs.curEditRepairImMeo.id;

      let typeRepair = storeImMeoRepairs.getTypeRepairById(
        storeImMeoRepairs.curEditRepairTypeRepairModelValue
      )?.name;

      // clear unused vars for selected type repair
      if (typeRepair == "ТО") {
        storeImMeoRepairs.curEditRepair.ro_8_7 = undefined;
        storeImMeoRepairs.curEditRepair.ro_8_9 = undefined;
        storeImMeoRepairs.curEditRepair.voltage = undefined;
        storeImMeoRepairs.curEditRepair.current = undefined;
        storeImMeoRepairs.curEditRepair.power = undefined;
      }
    };

    /**
     *
     */
    const onSaveRepair = async () => {
      let result_validate = await formEditRepairImMeo.value.validate();
      if (!result_validate) return;

      prepareRepairBeforeSaveUpdate();

      storeImMeoRepairs.saveRepair({
        imMeoRepair: storeImMeoRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "ImMeo repair has been added",
            progress: true,
          });

          storeImMeoRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    /**
     *
     */
    const onUpdateRepair = async () => {
      let result_validate = await formEditRepairImMeo.value.validate();
      if (!result_validate) return;

      prepareRepairBeforeSaveUpdate();

      storeImMeoRepairs.updateRepair({
        imMeoRepair: storeImMeoRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "ImMeo repair has been updated",
            progress: true,
          });

          storeImMeoRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    return {
      storeImMeoRepairs,
      storePositions,
      storeWorkers,
      formEditRepairImMeo,
      modelValueAutoGenVal,
      filterQselPositionsRemoved,
      onChangeQselPositionsRemoved,
      filterQselPositionsInstalled,
      onChangeQselPositionsInstalled,
      onIsAutoGeneratedValues,
      onUpdateRepair,
      onSaveRepair,
    };
  },
});
</script>
