<template>
  <q-form greedy ref="formEditRepairImMotor">
    <q-dialog
      v-model="storeImMotorRepairs.isShowRepairEditDialog"
      persistent
      :maximized="$q.platform.is.mobile ? true : false"
      transition-show="slide-up"
      transition-hide="slide-down"
    >
      <q-card>
        <q-card-section class="row items-center no-wrap">
          <div class="text-h6">
            Ремонт им. Мотор ({{
              storeImMotorRepairs.curEditRepairImMotor.serialNumber
            }}
            / {{ storeImMotorRepairs.curEditRepairImMotor.yearManufacture }})
          </div>
        </q-card-section>
        <q-separator />

        <q-card-section class="row items-center justify-center">
          <div class="q-gutter-md">
            <q-select
              outlined
              clearable
              v-model="storeImMotorRepairs.curEditRepairTypeRepairModelValue"
              :options="storeImMotorRepairs.typeRepairs"
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              option-value="id"
              option-label="name"
              emit-value
              map-options
              label-slot
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Тип ремонта
              </template>
            </q-select>

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeImMotorRepairs.curEditRepairPosRemovedModelValue"
              :options="storeImMotorRepairs.curEditRepairPosRemovedOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              @filter="filterQselPositionsRemoved"
              @update:model-value="onChangeQselPositionsRemoved"
              label-slot
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Позиция демонтажа
              </template>

              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <q-select
              outlined
              clearable
              use-input
              input-debounce="0"
              v-model="storeImMotorRepairs.curEditRepairPosInstalledModelValue"
              :options="storeImMotorRepairs.curEditRepairPosInstalledOptions"
              option-value="id"
              option-label="pos"
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              @filter="filterQselPositionsInstalled"
              @update:model-value="onChangeQselPositionsInstalled"
              label-slot
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                Позиция установки
              </template>

              <template v-slot:no-option>
                <q-item>
                  <q-item-section class="text-grey">
                    No results
                  </q-item-section>
                </q-item>
              </template>
            </q-select>

            <div
              class="q-px-lg"
              v-if="
                storeImMotorRepairs.getTypeRepairById(
                  storeImMotorRepairs.curEditRepairTypeRepairModelValue
                )?.name == 'ТР'
              "
            >
              <q-btn
                label="Generate values"
                color="primary"
                icon="auto_awesome"
                outline
                v-model="modelValueAutoGenVal"
                @click="onIsAutoGeneratedValues"
              />
              <br /><br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.resistanceInsulation"
                label-slot
                hint="Сопротивление изоляции обмоток статора, (МОм)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление изоляции обмоток статора, (МОм)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.resistanceWindingAB"
                label-slot
                hint="Сопротивление обмоток статора A-B, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора A-B, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.resistanceWindingBC"
                label-slot
                hint="Сопротивление обмоток статора B-С, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора B-С, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.resistanceWindingAC"
                label-slot
                hint="Сопротивление обмоток статора A-С, (Ом)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Сопротивление обмоток статора A-С, (Ом)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.currentNoLoadA"
                label-slot
                hint="Измерение тока холостого хода Фаза A, (А)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Измерение тока холостого хода Фаза A, (А)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.currentNoLoadB"
                label-slot
                hint="Измерение тока холостого хода Фаза B, (А)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Измерение тока холостого хода Фаза B, (А)
                </template>
              </q-input>
              <br />

              <q-input
                outlined
                clearable
                type="number"
                v-model="storeImMotorRepairs.curEditRepair.currentNoLoadC"
                label-slot
                hint="Измерение тока холостого хода Фаза C, (А)"
                reactive-rules
                :rules="[(val) => !!val || 'Field is required']"
              >
                <template v-slot:label>
                  <span class="text-weight-bold text-red">*</span>
                  Измерение тока холостого хода Фаза C, (А)
                </template>
              </q-input>
              <br />
            </div>

            <q-input
              outlined
              clearable
              v-model="storeImMotorRepairs.curEditRepair.dateRepair"
              label-slot
              mask="##.##.####"
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                <q-icon name="calendar_today" /> Дата ремонта
              </template>
              <template v-slot:append>
                <q-icon name="event" class="cursor-pointer">
                  <q-popup-proxy
                    ref="qDateProxy"
                    cover
                    transition-show="scale"
                    transition-hide="scale"
                  >
                    <q-date
                      v-model="storeImMotorRepairs.curEditRepair.dateRepair"
                      mask="DD.MM.YYYY"
                    >
                      <div class="row items-center justify-end">
                        <q-btn
                          v-close-popup
                          label="Close"
                          color="primary"
                          flat
                        />
                      </div>
                    </q-date>
                  </q-popup-proxy>
                </q-icon>
              </template>
            </q-input>

            <q-input
              outlined
              clearable
              v-model="storeImMotorRepairs.curEditRepair.desc"
              label="desc"
              type="textarea"
            />

            <q-select
              outlined
              clearable
              multiple
              use-chips
              stack-label
              v-model="storeImMotorRepairs.curEditRepairWorkersModelValue"
              :options="storeWorkers.workers"
              option-value="id"
              :option-label="
                (item) =>
                  item === null
                    ? 'Null value'
                    : `${item?.nameSecond} ${item?.nameFirst} ${item?.nameMiddle}`
              "
              emit-value
              map-options
              reactive-rules
              :rules="[(val) => !!val || 'Field is required']"
              label-slot
            >
              <template v-slot:label>
                <span class="text-weight-bold text-red">*</span>
                <q-icon name="perm_identity" /> Исполнители
              </template>
            </q-select>
          </div>
        </q-card-section>

        <q-card-section>
          <span class="text-weight-bold text-red">*</span>
          Indicates required fields
        </q-card-section>

        <q-separator />
        <q-card-actions align="right">
          <q-btn label="Cancel" color="primary" v-close-popup />
          <q-btn
            v-if="storeImMotorRepairs.curEditRepair.id"
            label="Update"
            color="amber-14"
            text-color="black"
            @click="onUpdateRepair"
          />
          <q-btn v-else label="Save" color="positive" @click="onSaveRepair" />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </q-form>
</template>

<script>
import { useQuasar } from "quasar";
import { defineComponent, ref } from "vue";
import { useImMotorRepairsStore } from "stores/equipments/imMotor/imMotorRepairs";
import { usePositionsStore } from "stores/positions";
import { useWorkersStore } from "stores/workers";
import * as utils from "src/utils";

export default defineComponent({
  name: "ImMotorFormRepairEdit",

  setup() {
    const $q = useQuasar();
    const storeImMotorRepairs = useImMotorRepairsStore();
    const storePositions = usePositionsStore();
    const storeWorkers = useWorkersStore();

    let formEditRepairImMotor = ref(null);
    let modelValueAutoGenVal = ref(null);

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsRemoved = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeImMotorRepairs.curEditRepairPosRemovedOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsRemoved = (val) => {
      storeImMotorRepairs.curEditRepair.fkPosRemovedId = val || null;
    };

    /**
     *
     * @param {*} val
     * @param {*} update
     * @param {*} abort
     */
    const filterQselPositionsInstalled = (val, update, abort) => {
      update(() => {
        if (val.length <= 0) return;

        const needle = val.toLowerCase();
        storeImMotorRepairs.curEditRepairPosInstalledOptions =
          storePositions.positions.filter(
            (pos) => pos.pos.toLowerCase().indexOf(needle) > -1
          );
      });
    };

    /**
     *
     * @param {*} val
     */
    const onChangeQselPositionsInstalled = (val) => {
      storeImMotorRepairs.curEditRepair.fkPosInstalledId = val || null;
    };

    /**
     *
     */
    const onIsAutoGeneratedValues = () => {
      storeImMotorRepairs.curEditRepair.resistanceInsulation =
        utils.getRandomBetween(1, 10) * 1000;

      // FIXME : Find normal odds for resistanceWinding
      let resistanceWinding = utils.getRandomBetween(0, 10);
      storeImMotorRepairs.curEditRepair.resistanceWindingAB = resistanceWinding;
      storeImMotorRepairs.curEditRepair.resistanceWindingBC = resistanceWinding;
      storeImMotorRepairs.curEditRepair.resistanceWindingAC = resistanceWinding;

      // FIXME : Find normal odds for currentNoLoad
      let currentNoLoad = utils.getRandomBetween(2, 3);
      storeImMotorRepairs.curEditRepair.currentNoLoadA = currentNoLoad;
      storeImMotorRepairs.curEditRepair.currentNoLoadB = currentNoLoad;
      storeImMotorRepairs.curEditRepair.currentNoLoadC = currentNoLoad;
    };

    /**
     *
     */
    const prepareRepairBeforeSaveUpdate = () => {
      storeImMotorRepairs.curEditRepair.fkTypeRepairId =
        storeImMotorRepairs.curEditRepairTypeRepairModelValue;
      storeImMotorRepairs.curEditRepair.fkWorkersIds = [
        ...storeImMotorRepairs.curEditRepairWorkersModelValue,
      ];

      storeImMotorRepairs.curEditRepair.fkImMotorId =
        storeImMotorRepairs.curEditRepairImMotor.id;

      let typeRepair = storeImMotorRepairs.getTypeRepairById(
        storeImMotorRepairs.curEditRepairTypeRepairModelValue
      )?.name;

      // clear unused vars for selected type repair
      if (typeRepair == "ТО") {
        storeImMotorRepairs.curEditRepair.ro_8_7 = undefined;
        storeImMotorRepairs.curEditRepair.ro_8_9 = undefined;
        storeImMotorRepairs.curEditRepair.voltage = undefined;
        storeImMotorRepairs.curEditRepair.current = undefined;
        storeImMotorRepairs.curEditRepair.power = undefined;
      }
    };

    /**
     *
     */
    const onSaveRepair = async () => {
      let result_validate = await formEditRepairImMotor.value.validate();
      if (!result_validate) return;

      prepareRepairBeforeSaveUpdate();

      storeImMotorRepairs.saveRepair({
        imMotorRepair: storeImMotorRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "ImMotor repair has been added",
            progress: true,
          });

          storeImMotorRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    /**
     *
     */
    const onUpdateRepair = async () => {
      let result_validate = await formEditRepairImMotor.value.validate();
      if (!result_validate) return;

      prepareRepairBeforeSaveUpdate();

      storeImMotorRepairs.updateRepair({
        imMotorRepair: storeImMotorRepairs.curEditRepair,
        okFunc: () => {
          $q.notify({
            color: "green-4",
            textColor: "white",
            position: "top",
            icon: "cloud_done",
            message: "ImMotor repair has been updated",
            progress: true,
          });

          storeImMotorRepairs.isShowRepairEditDialog = false;
        },
        errFunc: (err) => {
          $q.notify({
            color: "negative",
            position: "top",
            message: `Failed to save data to server: ${err}`,
            icon: "report_problem",
            progress: true,
          });
        },
      });
    };

    return {
      storeImMotorRepairs,
      storePositions,
      storeWorkers,
      formEditRepairImMotor,
      modelValueAutoGenVal,
      filterQselPositionsRemoved,
      onChangeQselPositionsRemoved,
      filterQselPositionsInstalled,
      onChangeQselPositionsInstalled,
      onIsAutoGeneratedValues,
      onUpdateRepair,
      onSaveRepair,
    };
  },
});
</script>
